apiVersion: v1
kind: ServiceAccount
metadata:
  name: redsky
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elasticsearch-setup
rules:
- apiGroups:
  - ""
  resources:
  - configmap
  - serviceaccount
  - service
  verbs:
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redsky-elasticsearch-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticsearch-setup
subjects:
- kind: ServiceAccount
  name: redsky
  namespace: default
